services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: minor_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/minor_db
      REDIS_URL: redis://redis:6379/0
      VACANCIES_PATH: /app/data/vacancies.json
    volumes:
      - ./backend:/app
      - ./backend/models:/app/models
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: .
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
